// Generated by CoffeeScript 1.6.1
(function() {
  var io, net, nn;

  require('coffee-script');

  nn = require('./nn/build/Release/nn.node');

  io = require('socket.io').listen(8080, {
    log: false
  });

  net = require('net');

  io.sockets.on('connection', function(socket) {
    var id, layers, synapses, _ref;
    id = socket.id;
    /*
    layers = []
    synapses = []
    for i in [0...3]
        layer = []
        for j in [0...10]
            neuron = {id: j + i * 10, activation: Math.random(), bias: Math.random()}
            layer.push(neuron)
        layers.push(layer)
    synapses = [{from: 0, to: 10}, {from: 9, to: 11}]
    */

    _ref = nn.getState(), layers = _ref[0], synapses = _ref[1];
    setInterval(function() {
      var _ref1;
      _ref1 = nn.getState(), layers = _ref1[0], synapses = _ref1[1];
      return socket.emit('update', layers, synapses);
    }, 500);
    return socket.emit('update', layers, synapses);
  });

}).call(this);
